Bstn jun 11 create navbar
juniorLeague/juniorbook pull request #8
Opened 2023-03-22 23:04 UTC by Bs-Tn

**Sign up button** : I didn't added a hover pseudo-class on it because i think the light primary is too light and its kind of weird but we can talk about it later

**Hamburger menu** : I didn't  implemented the expand feature for the menu its wasn't asked

2023-03-23 10:31 UTC, soner8 requested changes

2023-03-23 10:31 UTC, soner8 commented on src/components/common/UI/icons/hamburgerMenuOpen.tsx
Pour toute les icônes on va utiliser la lib: [ReactIcons](https://react-icons.github.io/react-icons/)

2023-03-23 10:31 UTC, soner8 commented on src/components/common/UI/icons/navBarIcon.tsx
Même chose, utiliser ReactIcons

2023-03-23 10:31 UTC, soner8 commented on src/components/navbar/navbar.tsx
> +  function handleScrollWindow(e: Event) {
Utilise une fonction fléchée : const handleScrollWindow = () => {}

2023-03-24 11:30 UTC, Alexandre-Chs commented on src/components/navbar.tsx
> +  useEffect(() => {
Tu dois mettre la logique handleScrollWindow dans le useEffect -> Si vous ne le faites pas, la référence de la fonction pourrait changer à chaque rendu et la fonction de nettoyage pourrait ne pas nettoyer correctement l'effet.

2023-03-24 11:30 UTC, Alexandre-Chs commented on src/components/navbar.tsx
Il serait intéressant de faire un customHook useIsScrolling qui prend la logique du scroll de l'user, et y mettre dans le useState et le useEffect, pour plus de clareté.

2023-03-24 21:23 UTC, Bs-Tn commented on src/components/navbar.tsx
Pour l'instant, je le laisse comme ça et si on a besoin de réutiliser cette fonctionnalité dans ce cas on pourra refactor et en faire un hook custom

2023-04-03 09:04 UTC, soner8 approved these changes

2023-04-03 09:09 UTC, merged